version: '3.7'
services:
    postgres:
        image: postgres:latest
        container_name: postgredb
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./create_currency_table.sql:/docker-entrypoint-initdb.d/create_currency_table.sql
        networks:
          - net  
    currency:
        image: currency
        container_name: currency
        networks: 
          - net
networks:
  net:


